[project]
name = "hotdot"
version = "0.2.0"
requires-python = ">=3.9"
description = "Stow based Dotfile manager."
license = "MIT"
dependencies = [
  "argcomplete",
]
maintainers = [
  {name = "Safae Ouajih", email = "ouajih.safae@gmail.com"},
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project.scripts]
hotdot = "hotdot.cli:main"

[project.urls]
Repository = "https://github.com/SafaeOuajih/hotdot.git"

[tool.setuptools.packages.find]
where = ["src"]
